### ISSUE TITLE
ridft issue?

### ISSUE THREAD

**Issue by PikachuSauvage** [grimme-lab/enso#9]
I just installed enso with DEMO version of turbomole. 

It turns out to have issue below:

Traceback (most recent call last):
  File "../enso.py", line 12232, in <module>
    main(argv=None)
  File "../enso.py", line 12139, in main
    ) = enso_startup(cwd,argv)
  File "../enso.py", line 9288, in enso_startup
    error_logical = input_object.processQMpaths(args, error_logical)
  File "../enso.py", line 8368, in processQMpaths
    print('    TURBOMOLE:    {}'.format(os.path.dirname(tmpath)))
  File "/home/jzhang/anaconda3/envs/enso/lib/python3.7/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

I checked the code around enso.py line 8368:

```
        if needtm:
            tmpath = shutil.which('ridft')
            print(type(tmpath),tmpath)
            print('    TURBOMOLE:    {}'.format(os.path.dirname(tmpath)))
```

Is it because the system can not find ridft? I can not find anywhere that I can install it. Is it because of the demo version?

Thanks very much for your help!

**Comment by fabothch** [comment]
Dear PikachuSauvage,

I am not sure that I understand you correctly. You have installed TURBOMOLE from a Demo?
If you can not find the binary ridft (e.g. by typing `which ridft` in your  terminal) than ENSO will not be able to run these calculations since the binary can not be found. ridft is needed for single point calculations with TURBOMOLE.  TURBOMOLE has to be set up correctly, before ENSO can do any TURBOMOLE related calculation. And you are correct in ridft has not been found. Maybe you have to source your TURBOMOLE installation?

Best, 

fabothch

**Comment by PikachuSauvage** [comment]
Dear fabothch,

Thanks very much for your reply. It helped a lot! 
Indeed, it's a problem of not correctly setting the path to TURBOMOLE. After setting correctly the path, the problem is solved. 

I don't know if TURBOMOLE is commercialized just recently or long before, but currently the only free version now is a demo version. I was therefore worried if the demo version is shrunk on functionalities and ridft was not part of it. Luckily it's not.

Just a little bit feedback for ENSO tutorial improvement: it turns out that the demo version only allows calculation of molecules contain 1-12, 50-60 or 110-120 atoms. However, in the ENSO tutorial, the demo molecules are not in these allowed size which seem to create a 100% not converged error.

Thanks again for your help! I am closing the issue.

**Comment by fabothch** [comment]
Just to give you an alternative: you can calculate NMR Spectra using ORCA and ENSO. The ORCA program is freely available for academic usage!
